name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main  # Cambia si usas otra rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 🔹 Checkout código
      uses: actions/checkout@v4

    - name: 🔹 Configurar .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x  # Asegúrate de usar la versión correcta

    - name: 🔹 Restaurar dependencias
      run: dotnet restore
      working-directory: src/ShortenApp  # Ajusta según tu estructura

    - name: 🔹 Compilar y publicar Blazor WASM
      run: dotnet publish -c Release -o publish
      working-directory: src/ShortenApp  # Ajusta según tu estructura

    - name: 🔹 Instalar Azure Static Web Apps CLI
      run: npm install -g @azure/static-web-apps-cli

    - name: 🔹 Desplegar en Azure Static Web Apps
      run: swa deploy ./publish/wwwroot -n upt-swa-153 --env production
      working-directory: src/ShortenApp  # Ajusta según tu estructura
      env:
        AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_CREDENTIALS }}
