name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 🔹 Checkout código
      uses: actions/checkout@v3

    - name: 🔹 Configurar .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x  # Asegúrate de usar la versión correcta

    - name: 🔹 Restaurar dependencias
      run: dotnet restore

    - name: 🔹 Compilar y publicar Blazor WASM
      run: dotnet publish -c Release -o publish

    - name: 🔹 Desplegar en Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_CREDENTIALS }}
        repo_token: ${{ secrets.GHCR_TOKEN }}
        action: "upload"
        app_location: "publish/wwwroot"